### PR TITLE
add request_type

### PR DESCRIPTION
**Pull request by chetankatke**
Update getAcessTocken function

### CODE REVIEW

**Comment by chetankatke** [comment]
I signed in

**Comment by chetankatke** [comment]
I signed it

**Comment by erickoledadevrel** [comment]
What problem does this change solve? What was the behavior before you added it?

**Comment by shokmaster** [comment]
@chetankatke this change is not aligned with the `oAuth2Client` object used in the Google API.

See the Google's client [README.md](https://github.com/googleapis/google-api-nodejs-client#generating-an-authentication-url) and the [Official sample OAuth2 client](https://github.com/googleapis/google-api-nodejs-client/blob/6817c39728b199b82af5478de5aef2cda51e969c/samples/sampleclient.js#L80).

**Comment by erickoledadevrel** [comment]
Closing due to lack of response.

**Comment by chetankatke** [comment]
Hey,

I just signed the petition "Prime Minister Mr Narendra Modi: Make attack on
Doctors a non bailable offence" and wanted to see if you could help by
adding your name.

Our goal is to reach 25,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/CXC4KrL6QG

Thanks!
Chetan

**Pull request closed without merging**
